name: Temp Publish To NPMJS

on:
  workflow_dispatch: 

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish npm'
    environment: npm
    
    strategy:
      matrix:
        node-version: [16.x]    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: |          
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish Loxodon.Framework.TextUGUI
        run: |
          cd $GITHUB_WORKSPACE/Loxodon.Framework.TextUGUI/Assets/LoxodonFramework/TextUGUI
          npm publish
          
